### PR TITLE
feat: Added instagram to Main Menu

### PR DESCRIPTION
**Pull request by tjklint**
Fixes issue #25 

Simply added one line to each of the main menu divs on all HTML pages.

### CODE REVIEW

**Review by tjklint — COMMENTED** [review]
Verified that all was added correctly.

**Comment by tjklint** [comment]
Should note, also commented out the Facebook and Wikipedia. Just in case they may be changed later.

**Comment by tjklint** [comment]
Fixed bug. Rechecking files.

**Review by tjklint — COMMENTED** [review]
Now added correctly.

**Comment by khathepham** [comment]
Bug Found: Home link on sidebar menus on every page was accidentally removed...

**Review by tjklint — COMMENTED** [review]
@khathepham

**Comment by khathepham** [comment]
LGTM

**Pull request merged**
